#!/usr/bin/env python3
"""Generate a connector test template for a new broker.

Usage:
    python3 connector/scripts/gen_broker_tests.py <broker> [--output PATH]

The generated file is a complete `#[cfg(test)] mod tests` skeleton covering every
dimension in TESTING_TEMPLATE.md. Fill in the `todo!(...)` sections by following
the Hyperliquid reference implementation (src/hyperliquid/), then mount it with
`#[cfg(test)] mod tests;` in the broker's mod.rs.
"""

import argparse
import pathlib

TEMPLATE = """//! {BROKER} connector tests (generated from connector/TESTING_TEMPLATE.md).
//!
//! Before running:
//!   1. Register the module in src/main.rs:
//!        #[cfg(feature = "{broker}")] pub mod {broker};
//!   2. Mount this file in src/{broker}/mod.rs:
//!        #[cfg(test)] mod tests;
//!   3. Replace every `todo!` with broker-specific assertions.
//!      Reference implementation: src/hyperliquid/ (see TESTING_TEMPLATE.md).
//!   4. Run: cargo test -p connector --features {broker}

#[cfg(test)]
mod tests {
    use super::*;
    use hftbacktest::types::{OrdType, Order, Side, Status, TimeInForce};

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    fn test_order(order_id: u64) -> Order {
        Order::new(
            order_id,
            300_000,
            0.1,
            1.0,
            Side::Buy,
            OrdType::Limit,
            TimeInForce::GTC,
        )
    }

    fn valid_config() -> String {
        todo!("build a minimal valid TOML config for {broker} (see connector/examples/{broker}.toml)")
    }

    // ------------------------------------------------------------------
    // 1. Config parsing
    // ------------------------------------------------------------------

    #[test]
    fn test_build_from_valid_config() {
        todo!("assert {BROKER_CAP}::build_from(&valid_config()) is Ok")
    }

    #[test]
    fn test_build_from_rejects_missing_required_field() {
        todo!("drop a required field from the config and assert build_from errors")
    }

    #[test]
    fn test_build_from_key_format_variants() {
        todo!("assert secret/api-key with and without a 0x prefix parse identically, if applicable")
    }

    #[test]
    fn test_build_from_defaults() {
        todo!("assert defaults such as trade mode / network / position side")
    }

    // ------------------------------------------------------------------
    // 2. Message deserialization (msg.rs)
    // ------------------------------------------------------------------

    #[test]
    fn test_deserialize_order_book() {
        todo!("parse a sample order-book payload; assert bids/asks structure and direction convention")
    }

    #[test]
    fn test_deserialize_trade() {
        todo!("parse a trade payload; assert side semantics map to buy/sell as documented")
    }

    #[test]
    fn test_deserialize_order_update() {
        todo!("parse an order-state update; assert status/quantity fields and field-name mapping")
    }

    #[test]
    fn test_deserialize_account_event() {
        todo!("parse fills/position events if the broker pushes them")
    }

    #[test]
    fn test_deserialize_error_response() {
        todo!("parse an error payload and assert the error variant is selected")
    }

    #[test]
    fn test_deserialize_unknown_fields_ignored() {
        todo!("parse a payload with extra fields; assert it does not error")
    }

    // ------------------------------------------------------------------
    // 3. Signing / auth vectors
    // ------------------------------------------------------------------

    #[test]
    fn test_signature_matches_official_vector() {
        todo!("sign a fixed payload with a fixed key; assert the result equals a vector generated by the official SDK")
    }

    #[test]
    fn test_signature_recovers_expected_identity() {
        todo!("if the broker uses recoverable signatures, recover the identity and compare with the derived one")
    }

    #[test]
    fn test_known_address_vector() {
        todo!("assert a fixed key derives the expected address/token")
    }

    // ------------------------------------------------------------------
    // 4. Wire format (order construction)
    // ------------------------------------------------------------------

    #[test]
    fn test_build_order_wire_price_and_qty_precision() {
        todo!("assert price follows tick size and qty follows lot size; strip trailing zeros")
    }

    #[test]
    fn test_build_order_wire_type_and_side_mapping() {
        todo!("assert order type / time-in-force / side map to the wire values")
    }

    #[test]
    fn test_build_order_wire_rejects_unsupported() {
        todo!("assert unsupported order types / time-in-force / sides return an InvalidArg error")
    }

    #[test]
    fn test_client_order_id_format() {
        todo!("assert the generated client order id matches the broker's constraints (prefix, charset, length)")
    }

    // ------------------------------------------------------------------
    // 5. Order manager state machine (ordermanager.rs)
    // ------------------------------------------------------------------

    #[test]
    fn test_order_manager_rest_then_ws_removal() {
        todo!("submit -> REST terminal update -> WS terminal update -> order removed, second update returns None")
    }

    #[test]
    fn test_order_manager_ws_then_rest_removal() {
        todo!("same as above with WS confirming first (both channel orders must be covered)")
    }

    #[test]
    fn test_order_manager_rejected_submit() {
        todo!("assert a rejected submit publishes Expired/Rejected and clears req")
    }

    #[test]
    fn test_order_manager_filled_submit() {
        todo!("assert a filled submit sets Filled, exec/leaves qty, and clears the lookup")
    }

    #[test]
    fn test_order_manager_cancel_failure_keeps_status() {
        todo!("assert a failed cancel does not change the order status and clears req")
    }

    #[test]
    fn test_order_manager_gc_removes_stale() {
        todo!("assert stale terminal orders are removed by gc while active ones survive")
    }

    #[test]
    fn test_order_manager_duplicate_order_id_rejected() {
        todo!("assert a second submit with the same (symbol, order_id) is rejected")
    }

    #[test]
    fn test_order_manager_orders_filter() {
        todo!("assert orders() filters by symbol and active status")
    }

    // ------------------------------------------------------------------
    // 6. Response parsing / error mapping
    // ------------------------------------------------------------------

    #[test]
    fn test_parse_submit_response_variants() {
        todo!("assert resting/filled/error branches of the submit response parser")
    }

    #[test]
    fn test_parse_cancel_response_variants() {
        todo!("assert success/error/empty branches of the cancel response parser")
    }

    #[test]
    fn test_error_mapping() {
        todo!("assert exchange error codes map to the connector's error enum")
    }

    // ------------------------------------------------------------------
    // 7. Feed / event parsing (pure functions from ws.rs)
    // ------------------------------------------------------------------

    #[test]
    fn test_channel_classification() {
        todo!("extract and test the channel dispatch rules (prefix vs exact match)")
    }

    #[test]
    fn test_side_to_event_mapping() {
        todo!("extract and test the trade side -> buy/sell event mapping")
    }

    #[test]
    fn test_position_delta() {
        todo!("extract and test how fills update the local position")
    }

    // ------------------------------------------------------------------
    // 7b. Funding rate (LiveEvent::Funding)
    // ------------------------------------------------------------------

    #[test]
    fn test_deserialize_funding_rate() {
        todo!("parse a sample funding-rate payload; assert the funding-rate and next-funding-time fields")
    }

    #[test]
    fn test_funding_timestamp_conversion() {
        todo!("assert the exchange's millisecond timestamp is converted to the event's nanosecond field")
    }

    #[test]
    fn test_funding_event_published() {
        todo!("feed a funding message into the stream handler; assert a LiveEvent::Funding is published with symbol/funding_rate/next_funding_time/exch_ts")
    }

    // ------------------------------------------------------------------
    // 8. E2E (testnet, ignored by default)
    // ------------------------------------------------------------------

    fn testnet_config() -> String {
        let key = std::env::var("{BROKER_UPPER}_TEST_PRIVATE_KEY")
            .expect("{BROKER_UPPER}_TEST_PRIVATE_KEY must be set");
        let account = std::env::var("{BROKER_UPPER}_TEST_ACCOUNT_ADDRESS").unwrap_or_default();
        todo!("build the testnet TOML config from {key} and {account}")
    }

    #[tokio::test]
    #[ignore = "requires a funded testnet account and env vars"]
    async fn e2e_order_roundtrip() {
        todo!("place a resting order far from the market, assert New, cancel, assert Canceled")
    }
}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("broker", help="broker module name, e.g. coinbase")
    parser.add_argument("--output", "-o", help="output path (default: src/<broker>/tests.rs)")
    args = parser.parse_args()

    broker = args.broker.lower()
    rendered = (
        TEMPLATE.replace("{broker}", broker)
        .replace("{BROKER_CAP}", broker.capitalize())
        .replace("{BROKER_UPPER}", broker.upper())
    )

    output = pathlib.Path(args.output) if args.output else pathlib.Path(
        "src", broker, "tests.rs"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered)

    print(f"generated: {output}")
    print()
    print("Next steps:")
    print(f"  1. In src/main.rs:  #[cfg(feature = \"{broker}\")] pub mod {broker};")
    print(f"  2. In src/{broker}/mod.rs:  #[cfg(test)] mod tests;")
    print(f"  3. Fill the todo!() sections following src/hyperliquid/ (see TESTING_TEMPLATE.md).")
    print(f"  4. Run: cargo test -p connector --features {broker}")


if __name__ == "__main__":
    main()
