[package]
name = "titan-connector-solana-plugin"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
connector = { path = "../../connector", default-features = false, features = ["solana"] }
serde_json = "1"
titan-plugin-engine = { path = "../titan-plugin-engine" }
